//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.VisualStudio.PowerTools.OptionsPage {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.VisualStudio.PowerTools.OptionsPage.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Show matches in the editor 的本地化字符串。
        /// </summary>
        internal static string AdornmentMatch {
            get {
                return ResourceManager.GetString("AdornmentMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Control click shows definitions in Peek 的本地化字符串。
        /// </summary>
        internal static string ControlClickOpensPeek {
            get {
                return ResourceManager.GetString("ControlClickOpensPeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Control click options 的本地化字符串。
        /// </summary>
        internal static string ControlClickOptions {
            get {
                return ResourceManager.GetString("ControlClickOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show matches in the margin 的本地化字符串。
        /// </summary>
        internal static string MarginMatch {
            get {
                return ResourceManager.GetString("MarginMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Match margin options 的本地化字符串。
        /// </summary>
        internal static string MatchMarginOptions {
            get {
                return ResourceManager.GetString("MatchMarginOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show a separator between methods in the editor 的本地化字符串。
        /// </summary>
        internal static string MethodSeparatorEnabled {
            get {
                return ResourceManager.GetString("MethodSeparatorEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show code structure in the editor 的本地化字符串。
        /// </summary>
        internal static string StructureAdornmentEnabled {
            get {
                return ResourceManager.GetString("StructureAdornmentEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show code structure in the margin 的本地化字符串。
        /// </summary>
        internal static string StructureMarginEnabled {
            get {
                return ResourceManager.GetString("StructureMarginEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show the code structure preview in the margin 的本地化字符串。
        /// </summary>
        internal static string StructurePreviewEnabled {
            get {
                return ResourceManager.GetString("StructurePreviewEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Structure visualizer options 的本地化字符串。
        /// </summary>
        internal static string StructureVisualizerOptions {
            get {
                return ResourceManager.GetString("StructureVisualizerOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compress blank lines 的本地化字符串。
        /// </summary>
        internal static string SyntacticFisheyeCompressBlankLines {
            get {
                return ResourceManager.GetString("SyntacticFisheyeCompressBlankLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compress lines that do not have any alphanumeric characters 的本地化字符串。
        /// </summary>
        internal static string SyntacticFisheyeCompressSimpleLines {
            get {
                return ResourceManager.GetString("SyntacticFisheyeCompressSimpleLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Syntactic line compression options 的本地化字符串。
        /// </summary>
        internal static string SyntacticFisheyeOptions {
            get {
                return ResourceManager.GetString("SyntacticFisheyeOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show time stamps in debug output 的本地化字符串。
        /// </summary>
        internal static string TimeStampMarginEnabled {
            get {
                return ResourceManager.GetString("TimeStampMarginEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Time stamp margin options 的本地化字符串。
        /// </summary>
        internal static string TimeStampMarginOptions {
            get {
                return ResourceManager.GetString("TimeStampMarginOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show hours in the time stamp margin 的本地化字符串。
        /// </summary>
        internal static string TimeStampMarginShowHours {
            get {
                return ResourceManager.GetString("TimeStampMarginShowHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show milliseconds in the time stamp margin 的本地化字符串。
        /// </summary>
        internal static string TimeStampMarginShowMilliseconds {
            get {
                return ResourceManager.GetString("TimeStampMarginShowMilliseconds", resourceCulture);
            }
        }
    }
}
